import type { Metadata } from 'next'

import { GeneralLayout } from '@/widgets/general-layout'
import './globals.css'
import { LanguageProvider } from './i18n/client'

export const metadata: Metadata = {
	title: 'Chulba',
	description: 'Generated by Myratgeldiyev',
}

export default function RootLayout({
	children,
	params: { lang },
}: Readonly<{
	children: React.ReactNode
	params: { lang: string }
}>) {
	return (
		<html lang='en'>
			<body className={''}>
				<GeneralLayout>
					<LanguageProvider initialLanguage={lang}>{children}</LanguageProvider>
				</GeneralLayout>
			</body>
		</html>
	)
}
