import { GeneralLayout } from '@/widgets/general-layout'
import type { Metadata } from 'next'
import './globals.css'
import { LanguageProvider } from './i18n/client'

export const metadata: Metadata = {
	title: 'Chulba',
	description: 'Generated by Myratgeldiyev',
	icons: {
		icon: '/favicon.png',
		shortcut: '/favicon.ico',
		apple: '/apple-touch-icon.png',
	},
}

export async function generateStaticParams() {
	return [{ lang: 'en' }, { lang: 'tk' }, { lang: 'ru' }]
}

type Props = {
	children: React.ReactNode
	params: Promise<{ lang: string }>
}

export default async function RootLayout({ children, params }: Props) {
	const { lang } = await params

	return (
		<html lang={lang}>
			<body>
				<LanguageProvider initialLanguage={lang}>
					<GeneralLayout>{children}</GeneralLayout>
				</LanguageProvider>
			</body>
		</html>
	)
}
