import { GeneralLayout } from '@/widgets/general-layout'
import type { Metadata } from 'next'
import './globals.css'
import { LanguageProvider } from './i18n/client'

export const metadata: Metadata = {
	title: 'Chulba',
	description: 'Generated by Myratgeldiyev',
}

type Props = {
	children: React.ReactNode
	params: { lang: string }
}

export default async function RootLayout({ children, params }: Props) {
	const { lang } = await params

	return (
		<html lang={lang}>
			<body>
				<GeneralLayout>
					<LanguageProvider initialLanguage={lang}>{children}</LanguageProvider>
				</GeneralLayout>
			</body>
		</html>
	)
}
