import type { Metadata } from 'next'

import { GeneralLayout } from '@/widgets/general-layout'
import './globals.css'

export const metadata: Metadata = {
	title: 'Chulba',
	description: 'Generated by Myratgeldiyev',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={''}>
				<GeneralLayout>{children}</GeneralLayout>
			</body>
		</html>
	)
}
